### ISSUE TITLE
[Request for CompetitiveCompany]

### ISSUE THREAD

**Issue by elihamster** [agmass/HandicapCompany#1]
I know this is the wrong mod but I also have a huge request regarding your other mod, CompetitiveCompany. I've been super intrigued about this game and some type of competitive mode and I believe yours really hit the mark with me and my friends and I wanted to make a request. Now before I say anything I just want to know I do not know how to code so I am not aware of the difficulties or nuances so excuse me if I come off a certain way. Could you please add configs so I can change the grace period time and the -200 penalty time (2 PM) and maybe a way to turn off pop-ups? I would greatly appreciate it.

**Comment by agmass** [comment]
Thank you so much for trying out the mods! I'll probably make a GitHub for competitive company soon but for now I'll definitely take this into consideration- mostly since it's quite simple. I'll try to do it now along with some additional patches

**Comment by agmass** [comment]
done! https://thunderstore.io/c/lethal-company/p/agmas/CompetitiveCompany/
